name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Tag
        id: latest_release
        run: |
          latest_tag=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "Latest release tag: $latest_tag"
          echo "::set-output name=tag::$latest_tag"

      - name: Credentials
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Prepare Build
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: |
          docker build -t ghcr.io/cat-ling/painterest:latest -t ghcr.io/cat-ling/painterest:${{ steps.latest_release.outputs.tag }} .
      
      - name: Push
        run: |
          docker push ghcr.io/cat-ling/painterest:latest
          docker push ghcr.io/cat-ling/painterest:${{ steps.latest_release.outputs.tag }}
