name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Ensure the token has write permissions to GitHub Packages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Credentials
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # Using GITHUB_TOKEN here

      - name: Prepare Build
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: |
          docker build -t ghcr.io/cat-ling/painterest:latest .

      - name: Push
        run: |
          docker push ghcr.io/cat-ling/painterest:latest
