name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Credentials
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      - name: Prepare Build
        uses: docker/setup-buildx-action@v2

      - name: Get Tag
        id: get_tag
        run: |
          # Fetch tags to ensure we have the latest
          git fetch --tags
          # Get the latest tag from the repository
          latest_tag=$(git describe --tags --abbrev=0 || echo "0.0.0")
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build -t ghcr.io/cat-ling/painterest:${{ env.latest_tag }} -t ghcr.io/cat-ling/painterest:latest .

      - name: Push
        run: |
          docker push ghcr.io/cat-ling/painterest:${{ env.latest_tag }}
          docker push ghcr.io/cat-ling/painterest:latest
